swagger: '2.0'
info:
  description: Organicity Annotation API
  version: '1.0-SNAPSHOT'
  title: Organicity Annotation API
  termsOfService: 'http://www.organicity.eu'
host: 'https://annotations.organicity.eu '
basePath: /
tags:
  - name: tag-controller
    description: Tag Controller
