swagger: '2.0'
info:
  title: Organicity Asset Directory
  description: |
    This API specifies the API of the OrganiCity Asset Directory.
    
    It comprises functionality for the following parts:
    - Querying available entities
    
    
  version: 0.1.0-testing
host: ec2-54-68-181-32.us-west-2.compute.amazonaws.com:8090
basePath: /v1/
schemes:
  - http

externalDocs:
  description: More information can be found on the OrganiCity website.
  url: http://www.organicity.eu/

definitions:
  Location:
    type: object
    description: The location of an entity.
    properties:
      latitude:
        type: number
      longitude:
        type: number
      city:
        type: integer
      country:
        type: string
      country_code:
        type: string
  Provider:
    type: object
    description: An Organicity Asset Provider.
    required: ['id','uuid']
    properties:
      id:
        type: integer
      uuid:
        type: string
      username:
        type: string
      avatar:
        type: string
      url: 
        type: string
      joined_at:
        type: string
      location:
        $ref: '#/definitions/Location'
  DataObject:
    type: object
    description: An Organicity Asset Data Object.
    required: ['id','attributes_id','value']
    properties:
      id:
        type: integer
      name:
        type: string
      unit:
        type: string
      updated_at:
        type: string
      attributes_id:
        type: string
      value:
        type: number
      prev_value: 
        type: number
  Data:
    type: object
    description: A list of sensor measurements.
    required: ['location','attributes']
    properties:
      recorder_at:
        type: string
      location:
        $ref: '#/definitions/Location'
      attributes:
        type: array
        items:
          $ref: '#/definitions/DataObject'
  Entity:
    type: object
    description: An Organicity Entity.
    required: ['uuid','id']
    properties:
      uuid:
        description: The UUID of this entity.
        type: string
        format: uuid
      id:
        type: integer
      name:
        type: string
      last_reading_at:
        type: string
      provider: 
        $ref: '#/definitions/Provider'
      data:
        $ref: '#/definitions/Data'
      entities_type:
        type: string
paths:
  /entities:
    get:
      description: |
        Gets `Entities` objects.
      responses:
        '200':
          description: Successful response
          schema:
            type: array
            items:
              $ref: '#/definitions/Entity'