swagger: '2.0'
info:
  version: '0.1'
  title: Organicity Assets Discovery Service
  description: |
    This API aims to create the foundations for a novel urban data observatory in the form of a service that allow various stakeholders (data scientists, city decision makers, organisations and citizens) to explore, with the intent to act, mixed static and real-time urban and social data streams and their exploitation in experimentation.

    It comprises the following functionalities:
    - Searching and filtering assets using multiple options
    - Retrieving information about: services, sites and providers
    - Retrieving assets data
    - Retrieving experiments and the associated assets

    *This API is the core engine of the [Organicity Urban Data Observatory](http://observatory.organicity.eu/) and it is designed following the [OASC](http://oascities.org/) principles, as an extension of the [NGSI 9/10](https://forge.fiware.org/plugins/mediawiki/wiki/fiware/index.php/FI-WARE_NGSI-10_Open_RESTful_API_Specification) standard, specially following the new [FIWARE-NGSI v2 Specification](http://telefonicaid.github.io/fiware-orion/api/v2/latest/)*

  termsOfService: 'http://www.organicity.eu'
  contact:
    name: Organicity Helpdesk
host: api.organicity.eu
basePath: /discovery/v0
securityDefinitions: {}
paths:
  '/assets?{asset_urn}&{last_updated}&{type}&{sort}&{filter}&{order}&{offset}&{page}&{per}&{sample}&{query}':
    get:
      description: 'Retrieve an assets using multiple criteria'
      operationId: List All Assets_
      produces:
      - application/json
      parameters:
      - name: asset_urn
        in: path
        required: true
        x-is-map: false
        type: string
        description: Filter assets by their Unique Resource Name
      - name: last_updated
        in: path
        required: true
        x-is-map: false
        type: string
        format: date-time
        description: Filter assets by last updated date
      - name: type
        in: path
        required: true
        x-is-map: false
        type: string
        description: Filter access by type
      - name: sort
        in: path
        required: true
        x-is-map: false
        type: string
        description: Sort assets. Supported values are to be defined.
      - name: filter
        in: path
        required: true
        x-is-map: false
        type: string
        description: Filter assets. Supported values are to be defined.
      - name: order
        in: path
        required: true
        x-is-map: false
        type: string
        description: Order assets DESC or ASC.
      - name: offset
        in: path
        required: true
        x-is-map: false
        type: integer
        format: int32
        description: Return assets with the given offset of N results.
      - name: page
        in: path
        required: true
        x-is-map: false
        type: integer
        format: int32
        description: Return assets for the given page.
      - name: per
        in: path
        required: true
        x-is-map: false
        type: integer
        format: int32
        description: Return N assets per page.
      - name: sample
        in: path
        required: true
        x-is-map: false
        type: integer
        format: int32
        description: Return a random sample of N assets.
      - name: query
        in: path
        required: true
        x-is-map: false
        type: string
        description: Return a list of assets based on metadatadatatata search
      responses:
        '200':
          description: ''
          schema:
            type: object
  '/assets/services':
    get:
      description: 'Return the services the assets belong to'
      operationId: List All Assets Services_
      produces:
      - application/json
      parameters: []
      responses:
        '200':
          description: ''
          schema:
            $ref: '#/definitions/ListAssetsServiceresponse'
  '/assets/services/{service}':
    get:
      description: 'Return a specific service'
      operationId: List Assets Service_
      produces:
      - application/json
      parameters:
      - name: service
        in: path
        required: true
        x-is-map: false
        type: string
        description: Filter assets by service
      responses:
        '200':
          description: ''
          schema:
            $ref: '#/definitions/ListAssetsServiceresponse'
  '/assets/sites':
    get:
      description: 'Return the sites the assets belong to'
      operationId: List All Assets Sites_
      produces:
      - application/json
      parameters: []
      responses:
        '200':
          description: ''
          schema:
            $ref: '#/definitions/ListAssetsSiteresponse'
  '/assets/sites/{site}':
    get:
      description: 'Return a specific site'
      operationId: List Assets Site_
      produces:
      - application/json
      parameters:
      - name: site
        in: path
        required: true
        x-is-map: false
        type: string
        description: Filter access by site
      responses:
        '200':
          description: ''
          schema:
            $ref: '#/definitions/ListAssetsSiteresponse'
  '/assets/providers':
    get:
      description: 'Return the providers the assets belong to'
      operationId: List All Assets Providers_
      produces:
      - application/json
      parameters: []
      responses:
        '200':
          description: ''
          schema:
            type: array
            items:
              $ref: '#/definitions/ListAllAssetsProvidersresponse'
  '/assets/providers/{provider}':
    get:
      description: 'Return a specific provider'
      operationId: List Assets Provider_
      produces:
      - application/json
      parameters:
      - name: provider
        in: path
        required: true
        x-is-map: false
        type: string
        description: Filter access by provider
      responses:
        '200':
          description: ''
          schema:
            $ref: '#/definitions/ListAssetsProviderresponse'
  '/assets/geo/search?{lat}&{long}&{radius}&{query}&{points}&{ip}&{city}':
    get:
      description: 'Return a list of assets filtered by geolocation'
      operationId: Get_Assets geo search_
      produces:
      - application/json
      parameters:
      - name: lat
        in: path
        required: true
        x-is-map: false
        type: string
        description: Center latitude for geographical queries
      - name: long
        in: path
        required: true
        x-is-map: false
        type: string
        description: Center longitude for geographical queries
      - name: radius
        in: path
        required: true
        x-is-map: false
        type: string
        description: Spherical radius for geographical queries
      - name: query
        in: path
        required: true
        x-is-map: false
        type: string
        description: At the moment only query="polygon" is supported
      - name: points
        in: path
        required: true
        x-is-map: false
        type: string
        description: Array of geographical coordinates
      - name: ip
        in: path
        required: true
        x-is-map: false
        type: string
        description: IP address
      - name: city
        in: path
        required: true
        x-is-map: false
        type: string
        description: "City name for geographical queries"
      responses:
        '200':
          description: ''
          schema:
            $ref: '#/definitions/ListAssetsProviderresponse'
  '/assets/metadata?{query}':
    get:
      description: 'Return a list of assets filtered by specific metadata'
      operationId: Get_Assets search metadata_
      produces:
      - application/json
      parameters:
      - name: query
        in: path
        required: true
        x-is-map: false
        type: string
        description: metadata query string
      responses:
        '200':
          description: ''
          schema:
            $ref: '#/definitions/RetrieveAssetbyURNresponse'
  '/assets/{asset_urn}':
    get:
      description: 'Return an assets by URN'
      operationId: Retrieve Asset by URN_
      produces:
      - application/json
      parameters:
      - name: asset_urn
        in: path
        required: true
        x-is-map: false
        type: string
        description: Unique Resource Name of the asset
      responses:
        '200':
          description: ''
          schema:
            $ref: '#/definitions/RetrieveAssetbyURNresponse'
  '/assets/{asset_urn}/data':
    get:
      description: The data model follows NGSI 9/10 model defined in Organicity Assets Directory.
      operationId: Retrieve Asset data by URN_
      produces:
      - application/json
      parameters:
      - name: asset_urn
        in: path
        required: true
        x-is-map: false
        type: string
        description: Unique Resource Name of the asset
      responses:
        '200':
          description: ''
          schema:
            $ref: '#/definitions/RetrieveAssetbyURNresponse'
  '/assets/{asset_urn}/data/v2':
    get:
      description: The data model follows NGSI v2 approach removing the original XML legacy. It also groups the data based on the Assets structure defined in D2.1 Section 4.5.1, this improve performance on data parsing and presentation.
      operationId: Retrieve Asset data in NGSI v2 by URN_
      produces:
      - application/json
      parameters:
      - name: asset_urn
        in: path
        required: true
        x-is-map: false
        type: string
        description: Unique Resource Name of the asset
      responses:
        '200':
          description: ''
          schema:
            $ref: '#/definitions/RetrieveAssetbyURNresponse'
  '/assets/{asset_urn}/nearby?{radius}&{city}&{query}&{points}':
    get:
      description: 'Retrieve assets geograpically close to other assets'
      operationId: Search Assets nearby to URN_
      produces:
      - application/json
      parameters:
      - name: asset_urn
        in: path
        required: true
        x-is-map: false
        type: string
        description: Unique Resource Name of the asset
      - name: radius
        in: path
        required: true
        x-is-map: false
        type: string
        description: Spherical radius for geographical queries
      - name: query
        in: path
        required: true
        x-is-map: false
        type: string
        description: At the moment only query="polygon" is supported
      - name: points
        in: path
        required: true
        x-is-map: false
        type: string
        description: Array of geographical coordinates. Assets lat and long are taken as starting point.
      - name: city
        in: path
        required: true
        x-is-map: false
        type: string
        description: "City name for geographical queries"
      responses:
        '200':
          description: ''
          schema:
            type: object
  '/experiments/{experiment_id}':
    get:
      description: 'Retrieve an experiment by the experiment id'
      operationId: List All Experiments_
      produces:
      - application/json
      parameters:
      - name: experiment_id
        in: path
        required: true
        x-is-map: false
        type: string
        description: "Unique Resource Name of the experiment"
      responses:
        '200':
          description: ''
          schema:
            $ref: '#/definitions/RetrieveAssetbyExperiment'
definitions:
  ListAssetsServiceresponse:
    title: List Assets Service response
    type: object
    properties:
      id:
        type: string
      type:
        type: string
      related:
        type: object
    required:
    - id
    - type
    - related
  ListAssetsSiteresponse:
    title: List Assets Site response
    type: object
    properties:
      id:
        type: string
      type:
        type: string
      context:
        type: object
      attributes:
        type: object
      links:
        type: object
    required:
    - id
    - type
    - context
    - attributes
    - links
  ListAllAssetsProvidersresponse:
    title: List All Assets Providers response
    type: object
    properties:
      id:
        type: string
      type:
        type: string
      links:
        type: object
      related:
        type: object
    required:
    - id
    - type
    - links
    - related
  ListAssetsProviderresponse:
    title: List Assets Provider response
    type: object
    properties:
      id:
        type: string
      type:
        type: string
      links:
        type: object
      related:
        type: object
    required:
    - id
    - type
    - links
    - related
  RetrieveAssetbyURNresponse:
    title: Retrieve Asset by URN response
    type: object
    properties:
      id:
        type: string
      type:
        type: string
      context:
        type: object
      related:
        type: object
    required:
    - id
    - type
    - context
    - related
  RetrieveAssetbyExperiment:
    title: Retrieve Asset by Experiment response
    type: object
    properties:
      id:
        type: string
      type:
        type: string
      context:
        type: object
      experimenterId:
        type: integer
      registered:
        type: string
        format: date-time   
      expirationTime:
        type: string
        format: date-time  
      startingTime:
        type: string
        format: date-time   
      status:
        type: string 
      experimentArea:
        type: object
        properties:
          latitude: 
            type: string
          longitude: 
            type: string
      keywords:
        type: array
        items: 
          type: string
      assets:
        type: array
        items: 
          type: object
          properties:
            id:
              type: string
            type:
              type: string
            context:
              type: object
            related:
              type: object
      # assets:
      #   $ref: '#/definitions/RetrieveAssetbyURNresponse'
    required:
    - id
    - type
    - context
