swagger: '2.0'
info:
  description: Organicity Datasource API
  version: '0.1'
  title: Organicity Datasource API
  termsOfService: 'http://www.organicity.eu'
  contact:
    name: Organicity Helpdesk
host: 'localhost:12345'
basePath: /
tags:
  - name: datasource
    description: Datasource
paths:
  '/api/v1/entities/{uuid}/readings':
    get:
      tags:
        - datasource
      summary: datasource
      operationId: datasourceUsingGET
      consumes:
        - application/json
      produces:
        - '*/*'
      parameters:
        - name: uuid
          in: path
          description: uuid
          required: true
          type: string
        - name: attribute_id
          in: query
          description: attribute_id
          required: true
          type: string
        - name: from
          in: query
          description: from
          required: true
          type: string
        - name: to
          in: query
          description: to
          required: true
          type: string
        - name: function
          in: query
          description: function
          required: false
          type: string
        - name: rollup
          in: query
          description: rollup
          required: false
          type: string
        - name: limit
          in: query
          description: limit
          required: false
          type: string
        - name: offset
          in: query
          description: offset
          required: false
          type: string
      responses:
        '200':
          description: OK
          schema:
            $ref: '#/definitions/Response'
        '401':
          description: Unauthorized
        '403':
          description: Forbidden
        '404':
          description: Not Found
definitions:
  Response:
    type: object
    properties:
      attribute_id:
        type: string
      entity_id:
        type: string
      from:
        type: string
      function:
        type: string
      readings:
        type: array
        items:
          $ref: '#/definitions/Reading'
      rollup:
        type: string
      to:
        type: string
  Reading:
    type: object
    properties:
      datetime:
        type: string
      value:
        type: string
