swagger: "2.0"
info:
  title: OrganiCity Experimentation Monitoring API
  description: Monitorisation of experiments taking place in OrganiCity platform
  version: "1.0.0"
host: organicity.eu
schemes:
  - https
basePath: /v1

securityDefinitions:
  oauth:
    type: oauth2
    flow: implicit
    authorizationUrl: https://organicity.eu/oauth/authorize/?client_id=CLIENT-ID&redirect_uri=REDIRECT-URI&response_type=token
    scopes:
      basic: to read any and all data related to OrganiCity
security:
  - oauth:
    - basic

paths:
  /experiments:
    get:
      summary: retrieve the list of experiments running in the OC platform
      description: ""
      security:
       - oauth:
         - basic
      produces:
        - application/json
      responses:
        200:
          description: an array of OC experiments
          schema:
            type: array
            items:
              $ref: '#/definitions/expdesc'
        401:
          description: authentication error
          schema:
            $ref: '#/definitions/Error'
        default:
          description: unexpected error
          schema:
            $ref: '#/definitions/Error'

  /experiments/{experimentId}:
    get:
      summary: find experiment by ID
      description: ""
      security:
       - oauth:
         - basic
      operationId: getexperimentById
      produces:
        - application/json
      parameters:
        - in: path
          name: experimentId
          description: ID of experiment that needs to be fetched
          required: true
          type: string
      responses:
        "404":
          description: site not found
        "200":
          description: successful operation
          schema:
            $ref: "#/definitions/expdesc"
        401:
          description: authentication error
          schema:
            $ref: '#/definitions/Error'
        default:
          description: unexpected error
          schema:
            $ref: '#/definitions/Error'

    delete:
      summary: deletes an experiment
      description: ""
      security:
       - oauth:
         - basic
      operationId: deleteexperiment
      produces:
        - application/json
      parameters:
        - in: path
          name: experimentId
          description: experiment ID to delete
          required: true
          type: string
      responses:
        "200":
          description: experiment removed
        401:
          description: authentication error
          schema:
            $ref: '#/definitions/Error'
        "404":
          description: experiment not found
        default:
          description: unexpected error
          schema:
            $ref: '#/definitions/Error'

  /experiments/{experimentId}/sources:
    get:
      summary: retrieve the list of sources for a given experiment.
      description: ""
      security:
       - oauth:
         - basic
      produces:
        - application/json
      parameters:
        - in: path
          name: experimentId
          description: experiment ID
          required: true
          type: string
      responses:
        200:
          description: an array of experiment sources
          schema:
            type: array
            items:
              $ref: '#/definitions/source'
        401:
          description: authentication error
          schema:
            $ref: '#/definitions/Error'
        default:
          description: unexpected error
          schema:
            $ref: '#/definitions/Error'
    post:
      summary: add new sources to a given OrganiCity experiment
      description: ""
      security:
       - oauth:
         - basic
      consumes:
        - application/json
      produces:
        - application/json
      parameters:
        - in: path
          name: experimentId
          description: experiment ID
          required: true
          type: string
        - in: body
          name: source
          description: source that wants to be added to the experiment facility
          required: true
          schema:
            $ref: "#/definitions/source"
      responses:
        "200":
          description: source added
          schema:
            $ref: "#/definitions/source"
        401:
          description: authentication error
          schema:
            $ref: '#/definitions/Error'
        default:
          description: unexpected error
          schema:
            $ref: '#/definitions/Error'

  /experiments/{experimentId}/statistics:
    get:
      summary: retrieve statistics for a given experiment.
      description: ""
      security:
       - oauth:
         - basic
      produces:
        - application/json
      parameters:
        - in: path
          name: experimentId
          description: experiment ID
          required: true
          type: string
      responses:
        200:
          description: an array of experiment statistics
          schema:
            type: array
            items:
              $ref: '#/definitions/statistics'
        401:
          description: authentication error
          schema:
            $ref: '#/definitions/Error'
        default:
          description: unexpected error
          schema:
            $ref: '#/definitions/Error'

definitions:
  experiment:
    type: object
    required:
      - id
      - name
      - contact
    properties:
      id:
        type: string
        description: unique identifier representing a specific OC experiment. Only lowercases allowed
      name:
        type: string
        description: full experiment name
      contact:
        type: string
        format: email
        description: contact email address

  expdesc:
    type: object
    required:
      - id
      - name
      - contact
      - prefix
      - since
    properties:
      id:
        type: string
        description: unique identifier representing a specific OC experiment. Only lowercases allowed
      name:
        type: string
        description: full experiment name
      contact:
        type: string
        format: email
        description: contact email address
      prefix:
        type: string
        description: urn
      since:
        type: string
        description: init experimentation date, i.e. 2016-01-01 T00:00Z

  source:
    type: object
    required:
      - type
      - url
      - public
    properties:
      type:
        type: string
        description: environmental, transportartion, trash,...
      url:
        type: string
        description: endpoint URL
      public:
        type: boolean

  statistics:
    type: object
    required:
      - id
      - type
      - url
      - since
      - value
    properties:
      id:
        type: integer
        format: int64
        description: a unique ID
      type:
        type: string
        description: mean, max, min,...
      url:
        type: string
        description: endpoint URL
      since:
        type: string
        description: init experimentation date, i.e. 2016-01-01 T00:00Z
      value:
        type: string
        description: precise value of the retrieved statistic
        
  Error:
    type: object
    required:
      - code
    properties:
      code:
        type: integer
        format: int32
      message:
        type: string