swagger: '2.0'
info:
  version: 0.0.1
  title: 'JubatusRestApi'
host: 195.220.224.231:9191
basePath: /v1
paths:
  /calculate/{type}:
    get:
      description: |
        Checks a sensor value for its validity and returns the score calulated by jubatus.
      produces: 
        - application/json
      parameters:
        - name: type 
          in: path
          description: The type of the sensor
          required: true
          type: string
          format: string
        - name: reading
          in: query
          description: the value of the sensor
          required: true
          type: number
          format: double
      responses:
        '200':
          description: Successful response
          schema:
            title: JubatusScore
            type: object
            properties:
              type:
                type: string
              reading:
                type: string
              score:
                type: string
        '404':
          description: Not Found Response
          schema:
            title: JubatusScore
            type: object
            properties:
              type:
                type: string
              reading:
                type: string
        '400':
          description: Bad Request Response
          schema:
            title: JubatusScore
            type: object
            properties:
              type:
                type: string
              reading:
                type: string
