swagger: '2.0'
info:
  version: 0.1.0-testing
  title: 'Orion Context Broker API'
basePath: /v1
paths:
  /contextEntities:
    # TODO: add Fiware-Service , Fiware-ServicePath, Accept and Content-Type headers here! (not sure how)
    get:
      description: "Retrieves information about context entities."
      parameters:
        - name: limit
          in: query
          description: Size of array
          required: false
          type: number
          format: double
      responses:
        '200':
          description: Successful response
          schema:
            type: object
            properties:
              contextElements:
                type: array 
                items: 
                  $ref: '#/definitions/ContextElement'
definitions:
  ContextElement:
    type: object
    properties:
      id:
        type: string
        description: 'The UUID of the ContextElement.'
      type:
        type: string
        description: 'The type of the ContextElement.'
        enum: ["urn:oc:entityType:iotdevice","urn:oc:entityType:smartphone"]
      isPattern:
        type: boolean
        description: 'Type of the ContextElement description. When isPattern is true in queries multiple ContextElements can be queried.'
        enum: ["true","false"]
      attributes:
        type: array
        description: 'A list of Attributes assosiated with this ContextElement.'
        items:
          $ref: '#/definitions/Attribute'
  Attribute:
    type: object
    description: "The Attributes can be used to provide information about the available sensor measurements, "
    properties:
      name:
        type: string
        description: 'Name of this attribute.'
        enum: ["name","description","position","TimeInstant",".*"]
      type:
        type: string
        description: 'Data type of this attribute.'
        enum: ["urn:oc:attributeType:name","urn:oc:attributeType:description","coords","urn:oc:datatype:ISO8601","urn:oc:attributeType:.*"]
      value:
        type: string
        description: 'The value of this attribute.'
      metadatas:
        type: array
        description: 'A list of Metadata assosiated with this Attribute.'
        items:
          $ref: '#/definitions/Metadata'

  Metadata:
    type: object
    description: "Metadata can be used to provide information about the units of measurements of the provided sensor measurements."
    properties:
      name:
        type: string
        description: 'Name of the metadata'
        enum: ["unit","datatype","location"]
      type:
        type: string
        description: 'Data type of the metadata.'
        enum: ["string","urn:oc:datatype:numeric"]
      value:
        type: string
        description: 'value of metadata'
