swagger: '2.0'
info:
  title: Organicity Accounts - Permission Component
  description: |
    Several functions of Organicity are not available to any user, but
    require additional permissions to be executed. This component
    streamlines the handling of reading, editing and assigning roles
    for specific users.

    The functionalities in this document are only available to the
    service accounts of clients, and require appropriate roles
    themselves. These roles are:

    * `accounts-permissions:readGlobalRoles`, which allows reading
      global roles assigned to a user.
    * `accounts-permissions:readLocalRoles`, which allows reading
      roles specific the requesting client assigned to a user.
    * `accounts-permissions:editGlobalRoles`, which allows adding or
      removing global roles to or from a user.
    * `accounts-permissions:editLocalRoles`, which allows adding or
      removing roles specific to the requesting client to or from a
      user.
    * `accounts-permissions:listUsers`, which allows listing of all
      users.

  version: 0.2.1-development

schemes:
  - https
host: accounts.organicity.eu
basePath: /permissions/

securityDefinitions:
  OrganicityPermissions:
    type: oauth2
    # scopes:
    #   viewRoles: Read assigned and available roles
    #   editRoles: Assign and revoke roles from users
    flow: accessCode
    authorizationUrl: https://accounts.organicity.eu/realms/organicity/protocol/openid-connect/auth
    tokenUrl: https://accounts.organicity.eu/realms/organicity/protocol/openid-connect/token

definitions:
  Role:
    title: A single role
    description: |
      The actual roles managed by the Organicity Permissions. Roles
      are represented by strings, which can come in two flavours: A
      role might be a global role, applying to all of Organicity, or
      it might be specific to a single tool (a Client from the view of
      Organicity Accounts). A tool-specific role is always prefixed
      with the tool name and a colon. For example, the global role to
      create a new asset is called: `createAsset`. In contrast, the
      specific role of an administrator of the Scenario Tool is
      called: `scenarios:administrator`.

      Note that tool-specific roles are only visible to the respective
      tools. Consequently, when a tool queries the Permission
      Component for the roles of a single user, only the global roles
      and the roles specific to the querying tool are returned.

      The following global roles are currently available. For a
      description of the purpose of these roles, please refer to the
      [Roles and Permissions in
      Organicity](https://docs.google.com/document/d/1Owz9RfvL2-jUAFtV_6nIe-jD4qlubq8RFAM2e7CNXoo/edit)
      document available on Google Drive, or the respective [API
      documentation](https://api.organicity.eu/).

      * `readProtectedAssets`
      * `createAssets`
      * `manageAssets`
      * `readProtectedData`
      * `createData`
      * `manageData`

      > TODO: Add remaining roles.

    type: object
    required:
      - role
    properties:
      role:
        type: string
        description: The name of the role
        pattern: "^[a-zA-Z][a-zA-Z0-9-_]+(:[a-zA-Z0-9-_]+)?$"
      experiment:
        type: string
        description: |
          An experiment identifier, denoting the experiment that this
          specific role applies to.

          This field only needs to be set for roles restricted to
          specific experiments. If a query specifies a such a role
          without supplying an experiment id, the query will fail.
    example:
      role: createAsset

  Error:
    title: An error state
    description: |
      These objects are returned when the server encounters an error
      on processing a request, and needs to explain further error
      details to the requesting client.
    type: object
    required:
      - error
    properties:
      error:
        type: string
        description: |
          A detailed explanation on why the request failed.
    example:
      { "error": "The requested role does not adhere to the required format." }

  UserIdentifier:
    title: A short user identifier
    description: |
      This is a simple record of only user id and name, to group
      a system-unique identifier together with a human-readable
      name of a user. This record is deliberatly kept small to
      not leak any privacy-related information.
    type: object
    required:
      - id
      - name
    properties:
      id:
        type: string
        description: |
          The unique and permanent user identifier.
      name:
        type: string
        description: |
          The self-appointed user name.
    example:
      { "id": "0dfc01f7-a234-4cbc-8e70-7ae361127dd4",
        "name": "jackie" }

paths:
  /users:
    get:
      summary: Retrieve a list of users

      description: |
        This endpoint supplies a list of available user names and
        userIds that can be used for the more detailed actions.

        Due to privacy resons, this endpoint only returns these two
        fields; more data can only be obtained when the respective
        user performs a successful login through the client and
        supplies an ID Token.

        The endpoint always only returns a part of the list of users
        (paginated), given by the offset (which defaults to `0`) and
        the page length (which defaults to the maximum value of `50`).
        If you want to query for more users, you have to make multiple
        calls to the api.

      produces:
        - application/json

      parameters:
        - name: offset
          in: query
          description: |
            The offset in the list of users, given as the amount of
            users to skip. Defaults to `0`, thus returning the start
            of the list.
          required: false
          type: integer
          minimum: 0
          default: 0

        - name: count
          in: query
          description: |
            The maximum amount of users to return as the result of the
            call. Only values between 1 and 50 are allowed, in order
            to limit the result size. Defaults to `50`.
          default: 50
          type: integer
          minimum: 1
          maximum: 50
          required: false

      responses:
        200:
          description: |
            The requested list of users has been extracted and is
            returned as the body of the reply. If no users matched
            the query (i.e. the offset is too high), an empty
            array may be returned.
          schema:
            type: array
            items:
              $ref: '#/definitions/UserIdentifier'
            description: |
              An array of user identifiers, along with the
              human-readable user name.
          examples:
            application/json:
              [{"id":"cf2c1723-3369-4123-8b32-49abe71c0e57",
              "name":"fbuether"},
              {"id":"0dfc01f7-a234-4cbc-8e70-7ae361127dd4",
              "name":"jackie"}]
        422:
          description: |
            The given query parameters where not valid. This might
            occur if either the given offset or count where negative,
            or if count was too large.
          schema:
            $ref: '#/definitions/Error'
          examples:
            application/json:
              { "error":
                "The given count is too large." }
        401:
          description: |
            The requesting client did not supply identify information
            (see [Security
            Definitions](#security-definition-OrganicityPermissions)).
        403:
          description: |
            The requesting client does not have sufficient permissions
            to list users.

  '/users/{userId}/roles':
    get:
      summary: Retrieves a list of all available roles of a user

      description: |
        This endpoint retrieves a list of all roles available to the
        supplied user and visible to the requesting tool. This
        includes global roles as well as roles specific to the
        requesting tool.

        Consequently, this call must be authorized with a tool token,
        i.e. the supplied Bearer Token must belong to tool that
        requests the list of roles.

      produces:
        - application/json

      # security:
      #   - OrganicityPermissions:
      #       - viewRoles

      parameters:
        - name: userId
          in: path
          description: |
            The identifier of the user, as given by the subject field
            in the user's ID Token (the authentication token handed
            out by Organicity Accounts on login).
          required: true
          type: string
      responses:
        200:
          description: |
            The request has been processed and the determined roles
            are returned.

            Note that for a user that has no (visible) roles, an empty
            list is returned.
          schema:
            type: array
            items:
              $ref: '#/definitions/Role'
            description: |
              An array of roles, where each role describes a
              role assigned to the user.
          examples:
            application/json:
              [{ "role": "createAsset"}, { "role": "searchAssets" },
               { "role": "manageExperiment", "experiment":
                 "d87c9025-61bf-4a16-83ec-ee66915832a1" }]
        401:
          description: |
            The requesting client did not supply identify information
            (see [Security
            Definitions](#security-definition-OrganicityPermissions)).
        403:
          description: |
            The requesting client does not have sufficient permissions
            to inspect the roles of users.
        404:
          description: |
            The supplied user ID does not denote an existing user.
    post:
      summary: Add a role to a user
      description: |
        This endpoint allows tools to assign roles to a specific user,
        effectively allowing the user to perform additional actions.

        This call must be authorized with a tool token, i.e. the
        supplied Bearer Token must belong to tool that performs the
        call to this endpoint.

      # security:
      #   - OrganicityPermissions:
      #       - editRoles

      produces: []
      parameters:
        - name: userId
          in: path
          description: |
            The identifier of the user, as given by the subject field
            in the user's ID Token (the authentication token handed
            out by Organicity Accounts on login).
          required: true
          type: string
        - name: role
          in: body
          description: |
            The new role to be assigned to the user. See the [definition
            of roles](#/definitions/Role) for possible values.

            Example: `{ "role": "createAsset" }`
          required: true
          schema:
            $ref: '#/definitions/Role'
      responses:
        201:
          description: |
            The given role was successfully assigned to the specified
            user. This reply is also returned if the role was already
            assigned to the user previously; in that case, no changes
            have been made.
        422:
          description: |
            The supplied role is not valid. This usually means that an
            experiment identifier was required as part of the role,
            but was not supplied.
          schema:
            $ref: '#/definitions/Error'
          examples:
            application/json:
              { "error":
                "An Experiment ID is required for the given role, but was not supplied." }
        401:
          description: |
            The requesting client did not supply identify information
            (see [Security
            Definitions](#security-definition-OrganicityPermissions)).
        403:
          description: |
            The requesting client does not have sufficient permissions
            to assign roles to users.
        404:
          description: |
            The supplied user ID does not denote an existing user.

  '/users/{userId}/roles/{roleName}':
    get:
      summary: Tests if a user is assigned a specific role

      description: |
        This endpoint can be used if a tool is not interested in the
        complete list of assigned roles, but wants to check one
        specific role for a user.

      produces: []


      # security:
      #   - OrganicityPermissions:
      #       - viewRoles

      parameters:
        - name: userId
          in: path
          description: |
            The identifier of the user, as given by the subject field
            in the user's ID Token (the authentication token handed
            out by Organicity Accounts on login).
          required: true
          type: string
        - name: roleName
          in: path
          description: |
            The role to be checked for. This needs to adhere to the
            format specified in the [Role Type
            Definition](#/definitions/Role).
          type: string
          required: true
        - name: experiment
          in: query
          description: |
            This field specifies an experiment to check against. The
            parameter should only be supplied if the given role
            requires an experiment identifier.
          required: false
          type: string

      responses:
        200:
          description: |
            The role is assigned to the user.
        422:
          description: |
            The supplied role is not valid. This usually means that an
            experiment identifier was required as part of the role,
            but was not supplied.
          schema:
            $ref: '#/definitions/Error'
          examples:
            application/json:
              { "error":
                "An Experiment ID is required for the given role, but was not supplied." }
        404:
          description: |
            The user ID does not describe a valid user, or the role
            name does not denote a valid role.
        401:
          description: |
            The requesting client did not supply identify information
            (see [Security
            Definitions](#security-definition-OrganicityPermissions)).
        403:
          description: |
            The requesting client does not have the permissions to
            inspect roles, or the client tried to inspect permissions
            that are not visible to the client (e.g. because they
            belong to a different tool).

    delete:
      summary: Removes a specific role from a user

      description: |
        This endpoint allows a requesting client to remove a role from
        a user, effectively revoking permissions or access to specific
        resources.

        This endpoint only allows a requesting tool to manipulate the
        global roles or the roles specific to itself. A tool cannot
        remove permissions assigned to the user that are specific to a
        different tool.

      produces: []

      # security:
      #   - OrganicityPermissions:
      #       - viewRoles

      parameters:
        - name: userId
          in: path
          description: |
            The identifier of the user, as given by the subject field
            in the user's ID Token (the authentication token handed
            out by Organicity Accounts on login).
          required: true
          type: string
        - name: roleName
          in: path
          description: |
            The role to be checked for. This needs to adhere to the
            format specified in the [Role Type
            Definition](#/definitions/Role).
          type: string
          required: true
        - name: experiment
          in: query
          description: |
            This field supplies an experiment identifier if the role
            to be deleted is specific for an experiment.
          required: false
          type: string

      responses:
        200:
          description: |
            The given role has been successfully removed from the
            supplied user.
        422:
          description: |
            The supplied role is not valid. This usually means that an
            experiment identifier was required as part of the role,
            but was not supplied.
          schema:
            $ref: '#/definitions/Error'
          examples:
            application/json:
              { "error":
                "An Experiment ID is required for the given role, but was not supplied." }
        404:
          description: |
            The user ID does not describe a valid user, or the role
            name does not denote a valid role.
        401:
          description: |
            The requesting client did not supply identify information
            (see [Security
            Definitions](#security-definition-OrganicityPermissions)).
        403:
          description: |
            The requesting client does not have the permissions to
            remove roles.
