#%RAML 0.8
title: Questionnaire
version: 1
baseUri: http://dev.itm.uni-luebeck.de/organicity-scenario-tool/
/questionnaire:
  displayName: Questionnaire
  description: Handles the current questionnaire to be used with the scenario tool.
  get:
    description: Returns the currently active questionnaire, or a list of all
          questionnaires if requested.

          If no version is supplied, this will return the current
          questionnaire. Usually, questionnaires are versioned in increasing
          numbers, so if the current questionnaire has version number 7,
          the previous versions can be requested by passing version as 6, 5,
          and so on.
    queryParameters:
      version:
        description: The requested version, or `all` if all versions should be returned.
        example: 9
        displayName: Version
        default: The newest available version
        type: string
        required: false
    responses:
      200:
        description: If successful, this returns the current questionnaire if no
            version was specificed, or the questionnaire of the specified
            version. If all versions are requested, this returns a list of
            questionnaire objects.
        body:
          application/json:
            example: |
              {
                "questions": [
                  {
                    "values": [
                      {
                        "weight": -1,
                        "value": "This does not affect me."
                      },
                      {
                        "weight": 0,
                        "value": "Don't really know, maybe?"
                      },
                      {
                        "weight": 1,
                        "value": "Yes, I can use that."
                      }
                    ],
                    "text": "Does this idea apply to your daily life?",
                    "tech": false
                  },
                  {
                    "values": [
                      {
                        "weight": -1,
                        "value": "No"
                      },
                      {
                        "weight": 1,
                        "value": "Yes"
                      }
                    ],
                    "text": "Is this scenario plausible?",
                    "tech": true
                  }
                ],
                "explanation":
                  "Please rate the scenario provided from your personal perspective.",
                "description": "Second revision of initial questionnaire, fixed typos.",
                "version": 2
              }
            schema: |
              {
                "$schema": "http://json-schema.org/draft-03/schema",
                "questionnaire": {
                  "version": {
                    "type": "int",
                    "required": "true"
                  }
                }
              }
      404:
        description: Returned if no questionnaire with the given version number exists.