FORMAT: 1A

# Questionnaires

This API specifices access to the questionnaire of the scenario tool.

# Group Questionnaires

## Resource /questionnaire [/questionnaire{?version}]

### List one specific or all questionnaires [GET]

Returns the currently active questionnaire, or a list of all questionnaires if requested.

If no version is supplied, this will return the current questionnaire. Usually, questionnaires are versioned in increasing numbers, so if the current questionnaire has version number 7, the previous versions can be requested by passing version as 6, 5, and so on.


+ Parameters

    + version: `9` (string, optional) - The requested version. This may be a version string of a questionnaire or `all` to request all available versions as a list.

+ Response 200 (application/json)

    - If successful, this returns the current questionnaire if no version was specificed, or the questionnaire of the specified version.
    - If all versions are requested, this returns a list of questionnaire objects.

    + Body

            {
              "questions": [
                {
                  "values": [
                    {
                      "weight": -1,
                      "value": "This does not affect me."
                    },
                    {
                      "weight": 0,
                      "value": "Don't really know, maybe?"
                    },
                    {
                      "weight": 1,
                      "value": "Yes, I can use that."
                    }
                  ],
                  "text": "Does this idea apply to your daily life?",
                  "tech": false
                },
                {
                  "values": [
                    {
                      "weight": -1,
                      "value": "No"
                    },
                    {
                      "weight": 1,
                      "value": "Yes"
                    }
                  ],
                  "text": "Is this scenario plausible?",
                  "tech": true
                }
              ],
              "explanation": "Please rate the scenario provided from your personal perspective.",
              "description": "Second revision of initial questionnaire, fixed typos.",
              "version": 2
            }

    + Schema

            {
            }

+ Response 404

    Returned if no questionnaire with the given version number exists.

    + Body


### Perform cosmetic changes on the current questionnaire. [PATCH]

Updates the current questionnaire. Only used for cosmetic updates.

+ Request (application/json)

    The body of this request must contain the updated questionnaire.

    + Body

            {
              "description": "Second revision of initial questionnaire, fixed typos.",
              "explanation": "Please rate the scenario provided from your personal perspective.",
              "questions": [
                  {
                      "tech": false,
                      "text": "Does this idea apply to your daily life?",
                      "values": [
                          {
                              "value": "This does not affect me.",
                              "weight": -1
                          },
                          {
                              "value": "Don't really know, maybe?",
                              "weight": 0
                          },
                          {
                              "value": "Yes, I can use that.",
                              "weight": 1
                          }
                      ]
                  },
                  {
                      "tech": true,
                      "text": "Is this scenario plausible?",
                      "values": [
                          {
                              "value": "No",
                              "weight": -1
                          },
                          {
                              "value": "Yes",
                              "weight": 1
                          }
                      ]
                  }
              ],
              "version": 2
              }

+ Response 200 (application/json)

    The questionnaire has been updated. Returns the new questionnaire,
    including the updated version number.

    + Body

            {
              "description": "Second revision of initial questionnaire, fixed typos.",
              "explanation": "Please rate the scenario provided from your personal perspective.",
              "questions": [
                  {
                      "tech": false,
                      "text": "Does this idea apply to your daily life?",
                      "values": [
                          {
                              "value": "This does not affect me.",
                              "weight": -1
                          },
                          {
                              "value": "Don't really know, maybe?",
                              "weight": 0
                          },
                          {
                              "value": "Yes, I can use that.",
                              "weight": 1
                          }
                      ]
                  },
                  {
                      "tech": true,
                      "text": "Is this scenario plausible?",
                      "values": [
                          {
                              "value": "No",
                              "weight": -1
                          },
                          {
                              "value": "Yes",
                              "weight": 1
                          }
                      ]
                  }
              ],
              "version": 3
              }

+ Response 401

    The user is not authenticated.

    + Body

+ Response 403

    The authenticated user is not authorised, usually because he does
    not have an administrator role.

    + Body